name: Pipeline
on:
  push:
    branches:
    - "*"
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn run specs_without_eslint
